/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_IFRAME "m"
# define VAR_IRESOLUTION "v"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)uniform vec4 v;"
 "layout(location=1)uniform int m;\n"
 "#define PI 3.1415926\n"
 "vec3 s(in float v,in vec3 m,in vec3 y,in vec3 i,in vec3 x)"
 "{"
   "return m+y*cos(6.28318*(i*v+x));"
 "}"
 "vec3 s(float v)"
 "{"
   "return s(v,vec3(.5,.5,.5),vec3(.5,.5,.5),vec3(1.,1.,1.),vec3(0.,.33,.67));"
 "}"
 "vec2 n(vec2 v)"
 "{"
   "v+=1.61803;"
   "vec3 f=fract(vec3(v.xyx)*vec3(.1031,.103,.0973));"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.xx+f.yz)*f.zy);"
 "}"
 "const uint d=1103515245U;"
 "vec3 t(vec3 v)"
 "{"
   "uvec3 f=uvec3(v);"
   "f=(f>>8U^f.yzx)*d;"
   "f=(f>>8U^f.yzx)*d;"
   "f=(f>>8U^f.yzx)*d;"
   "return vec3(f)*(1./float(-1U));"
 "}"
 "float x(vec3 v)"
 "{"
   "return t(v).x;"
 "}"
 "vec2 e(vec2 v)"
 "{"
   "float f=v.x*2.*PI,i=sqrt(v.y);"
   "return vec2(i*cos(f),i*sin(f));"
 "}"
 "vec3 f(vec2 v)"
 "{"
   "return vec3(.2);"
 "}"
 "bool k;\n"
 "#define saturate(x)clamp(x,0.,1.)\n"
 "float e(float v,float y,float x)"
 "{"
   "float f=clamp(.5+.5*((v-y)/x),0.,1.);"
   "return(1.-f)*v+f*y-f*(1.-f)*x;"
 "}"
 "float f(float v,float m,float f)"
 "{"
   "return-e(-v,-m,f);"
 "}"
 "float n(float v,float f,float y)"
 "{"
   "vec2 x=max(vec2(y-v,y-f),vec2(0));"
   "return max(y,min(v,f))-length(x);"
 "}"
 "float s(float v,float f,float y)"
 "{"
   "vec2 x=max(vec2(y+v,y+f),vec2(0));"
   "return min(-y,max(v,f))+length(x);"
 "}"
 "float t(float v,float f,float x)"
 "{"
   "return min(e(v,f,x),n(v,f,x));"
 "}"
 "float x(float v,float m,float x)"
 "{"
   "return max(f(v,m,x),s(v,m,x));"
 "}"
 "void e(inout vec2 v,float x)"
 "{"
   "v=cos(x)*v+sin(x)*vec2(v.y,-v.x);"
 "}"
 "void r(inout vec2 v)"
 "{"
   "v=(v+vec2(v.y,-v.x))*sqrt(.5);"
 "}"
 "vec3 f(vec3 v,float f)"
 "{"
   "return e(v.yz,f),v;"
 "}"
 "vec3 n(vec3 v,float f)"
 "{"
   "return e(v.xz,f),v;"
 "}"
 "vec3 r(vec3 v,float f)"
 "{"
   "return e(v.xy,f),v;"
 "}"
 "float h(vec3 v)"
 "{"
   "return min(min(v.x,v.y),v.z);"
 "}"
 "float l(vec3 v)"
 "{"
   "return max(max(v.x,v.y),v.z);"
 "}"
 "float p(vec2 v)"
 "{"
   "return max(v.x,v.y);"
 "}"
 "float h(vec3 v,vec3 x)"
 "{"
   "vec3 f=abs(v)-x;"
   "return length(max(f,vec3(0)))+l(min(f,vec3(0)));"
 "}"
 "float l(vec2 v,vec2 x)"
 "{"
   "vec2 f=abs(v)-x;"
   "return length(max(f,vec2(0)))+p(min(f,vec2(0)));"
 "}struct Material{vec3 albedo;float specular;float roughness;};struct Model{float d;vec3 uvw;vec3 albedo;int id;};"
 "Material p(Model v,inout vec3 x)"
 "{"
   "int f=v.id;"
   "vec3 m=v.uvw;"
   "return Material(v.albedo,0.,0.);"
 "}"
 "float i;"
 "mat3 s(vec3 v,vec3 f)"
 "{"
   "vec3 x=normalize(v),i=normalize(cross(x,f)),y=normalize(cross(i,x));"
   "return mat3(i,x,y);"
 "}"
 "vec3 h(vec3 v,vec3 f,vec3 x)"
 "{"
   "return v*s(f,x);"
 "}"
 "float t(vec3 v,vec3 f)"
 "{"
   "float i=h(f,v);"
   "i=max(i,-abs(f.x));"
   "i=max(i,-(i+h(v)*.333));"
   "return i;"
 "}"
 "float e(vec3 v,vec3 f,vec3 i,float y)"
 "{"
   "i.y=max(i.y,.5*v.y/f.y);"
   "i.y-=v.y*.5;"
   "v.y*=.5;"
   "vec3 m=i;"
   "float r=1e+12;"
   "for(int d=0;d<int(f.x);d++)"
     "{"
       "for(int s=0;s<int(f.y);s++)"
         "{"
           "for(int M=0;M<int(f.z);M++)"
             "{"
               "i=m;"
               "vec3 l=vec3(d,s,M);"
               "i-=((l+.5)/f-.5)*v*2.;"
               "vec3 P=v/f,c=t(l+11.+y);"
               "i-=(c*2.-1.)*P*.5;"
               "float n=x(l*10.+27.+y);"
               "P*=mix(.6,1.5,n);"
               "P.xz*=mix(1.8,.45,pow(float(s)/(f.y-1.),.5));"
               "float z=h(i,P);"
               "z=max(z,-abs(i.x));"
               "if(c.z>.5&&l.y>0.)"
                 "z=max(z,-abs(i.y-(n*2.-1.)*P.y*.5));"
               "r=min(r,z);"
             "}"
         "}"
     "}"
   "r=max(r,-(r+h(v/f)*.5));"
   "return r;"
 "}"
 "float l(vec3 v,vec3 f,vec3 i)"
 "{"
   "v*=.9;"
   "i.y-=v.y*.5;"
   "v.y*=.5;"
   "vec3 m=i;"
   "float y=1e+12;"
   "for(int r=0;r<int(f.x);r++)"
     "{"
       "for(int d=0;d<int(f.y);d++)"
         "{"
           "for(int s=0;s<int(f.z);s++)"
             "{"
               "i=m;"
               "vec3 l=vec3(r,d,s);"
               "i-=((l+.5)/f-.5)*v*2.;"
               "vec3 M=v/f;"
               "float z=x(l+15.);"
               "M*=mix(1.1,1.75,z);"
               "float c=h(i,M)+.01;"
               "if(l==vec3(0))"
                 "c=max(c,-abs(i.x));"
               "c=max(c,-y);"
               "y=min(y,c);"
             "}"
         "}"
     "}"
   "y=max(y,-(y+h(v/f)*.5));"
   "return y;"
 "}"
 "float c(vec3 v)"
 "{"
   "float f=1e+12,x=.2;"
   "f=e(vec3(.35,1.6,.35),vec3(2,3,2),h(v-vec3(.8,0,-.8),vec3(.2,1,-.5),vec3(1,0,1)),0.);"
   "f=e(f,t(vec3(.13),h(v-vec3(1.8,-.15,-.3),vec3(0,1,0),vec3(1,0,-.25))),x);"
   "f=e(f,l(vec3(.3,.35,.3),vec3(2,1,2),h(v-vec3(-.3,0,.5),vec3(0.,1,.2),vec3(0.,0,1))-vec3(0,-.2,0)),x);"
   "f=e(f,e(vec3(.15,1.,.15),vec3(1,3,1),h(v-vec3(-1.8,-.15,-2.3),vec3(-1,2,-.5),vec3(-1,0,-2)),11.),x);"
   "return f;"
 "}"
 "Model P(vec3 v)"
 "{"
   "vec2 f=vec2(.43,.43);"
   "e(v.yz,(.5-f.y)*PI);"
   "e(v.xz,(.5-f.x)*PI*2.5);"
   "v.y+=.6;"
   "v.xz-=vec2(-1,1)*.4;"
   "float y=7.,x=c(v),r=v.y+.25;"
   "r=e(r,length(v-vec3(.6,-2.5,-.7))-2.5,.6);"
   "r=e(r,length(v-vec3(-.3,-.5,.5))-.5,.4);"
   "float m=pow(x+.333,.5)*1.5;"
   "r+=cos(max(m,0.)*y*PI*2.)*.015;"
   "Model o=Model(r,v,vec3(3),3),n=Model(x*i,v,vec3(1),1);"
   "if(n.d<o.d)"
     "o=n;"
   "return o;"
 "}"
 "const float y=1.73205;"
 "vec3 M(in vec3 v)"
 "{"
   "vec3 f=vec3(0.);"
   "for(int i=0;i<4;i++)"
     "{"
       "vec3 x=.5773*(2.*vec3(i+3>>1&1,i>>1&1,i&1)-1.);"
       "f+=x*P(v+.001*x).d;"
     "}"
   "return normalize(f);"
 "}"
 "vec3 H=normalize(vec3(5,2,2))*2.;struct Hit{Model model;vec3 pos;float len;};"
 "Hit M(vec3 v,vec3 f,float x,float y)"
 "{"
   "vec3 i;"
   "float r,d=0.;"
   "Model m;"
   "for(int s=0;s<200;s++)"
     "{"
       "i=v+f*r;"
       "m=P(i);"
       "r+=m.d*y;"
       "if(abs(m.d)/r<.0002)"
         "break;"
       "if(r>x)"
         "{"
           "m.id=0;"
           "break;"
         "}"
     "}"
   "return Hit(m,i,r);"
 "}"
 "Hit P(vec3 v,vec3 f,float x,float y)"
 "{"
   "vec3 i;"
   "float r=0.,m=0.;"
   "Model d;"
   "float s=0.;"
   "for(float M=0.;M<300.;M++)"
     "{"
       "r+=m;"
       "i=v+r*f;"
       "d=P(i);"
       "m=d.d;"
       "s+=1.;"
       "if(abs(d.d)/r<.0002)"
         "{"
           "break;"
         "}"
       "if(r>=x)"
         "{"
           "r=x;"
           "d.id=0;"
           "break;"
         "}"
     "}"
   "return Hit(d,i,r);"
 "}"
 "vec3 w(vec3 v)"
 "{"
   "vec3 f=cross(vec3(-1,-1,.5),v);"
   "return f;"
 "}"
 "vec3 M(vec3 v,float f,vec2 x)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(w(v)),i=normalize(cross(v,y));"
   "vec2 m=x;"
   "m.x=m.x*2.*PI;"
   "m.y=pow(m.y,1./(f+1.));"
   "float d=sqrt(1.-m.y*m.y);"
   "return cos(m.x)*d*y+sin(m.x)*d*i+m.y*v;"
 "}"
 "vec3 P(vec3 v,float f,vec2 x)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(w(v)),i=normalize(cross(v,y));"
   "vec2 m=x;"
   "m.x=m.x*2.*PI;"
   "m.y=1.-m.y*f;"
   "float d=sqrt(1.-m.y*m.y);"
   "return cos(m.x)*d*y+sin(m.x)*d*i+m.y*v;"
 "}"
 "vec3 a=vec3(.9,.83,1);"
 "float M(vec3 v,vec3 f,vec3 m,vec3 x,vec3 y,out vec2 i)"
 "{"
   "float d=dot(x,m-v)/dot(f,x);"
   "vec3 r=v+d*f,z=cross(x,y),c=cross(x,z);"
   "r-=m;"
   "i=vec2(dot(z,r),dot(c,r));"
   "return max(sign(d),0.);"
 "}"
 "mat3 u(vec2 v)"
 "{"
   "float f=v.x,x=v.y,y=cos(f),i=cos(x),m=sin(f),d=sin(x);"
   "return mat3(i,-d*-m,-d*y,0,y,m,d,i*-m,i*y);"
 "}"
 "mat3 b;"
 "vec3 M(vec3 v,vec3 f)"
 "{"
   "v=-v;"
   "f=-f;"
   "v*=b;"
   "f*=b;"
   "vec2 x;"
   "vec3 i=vec3(-6);"
   "float y=M(v,f,i,normalize(i),normalize(vec3(-1,1,0)),x),r=smoothstep(.75,0.,l(x,vec2(.5,2))-1.);"
   "r*=smoothstep(6.,0.,length(x));"
   "return vec3(r)*y*2.;"
 "}"
 "vec4 o(vec2 f)"
 "{"
   "vec2 x=n(f+float(m)*y);"
   "i=1.;"
   "b=u((vec2(81.5,119)/vec2(187)*2.-1.)*2.);"
   "vec2 r=(-v.xy+2.*f)/v.y;"
   "r+=2.*(x-.5)/v.xy;"
   "vec3 d=vec3(0);"
   "float z=3.;"
   "vec3 c=vec3(0,0,1.5)*z,l=vec3(0,0,0);"
   "c.xy+=e(x)*.05;"
   "x=n(x);"
   "vec3 o=normalize(l-c),I=normalize(cross(vec3(0,1,0),o)),H=normalize(cross(o,I));"
   "mat3 w=mat3(-I,H,o);"
   "vec3 k=normalize(w*vec3(r.xy,z)),g=c;"
   "Hit t=P(g,k,6.*z,1.);"
   "float h=t.len;"
   "vec3 U,q,F;"
   "Material C;"
   "vec3 Z=vec3(1),Y=a;"
   "int X=t.model.id==1?10:5;"
   "float W=x.y,V=0.,T,S;"
   "bool R=t.model.id==1;"
   "for(int Q=0;Q<X;Q++)"
     "{"
       "if(Q>0)"
         "x=n(x),t=P(g,k,6.,1.);"
       "if(i<0.)"
         "V+=t.len;"
       "if(t.model.id==0)"
         "{"
           "break;"
         "}"
       "U=M(t.pos);"
       "C=p(t.model,U);"
       "Z*=C.albedo;"
       "if(t.model.id==1)"
         "{"
           "q=reflect(k,U);"
           "d+=M(t.pos,q)*.5;"
           "d+=pow(max(1.-abs(dot(k,U)),0.),5.)*.1;"
           "d*=vec3(.85,.85,.98);"
           "T=mix(1.2,1.8,W);"
           "T=i<0.?T:1./T;"
           "F=refract(k,U,T);"
           "bool O=F==vec3(0);"
           "k=O?q:F;"
           "i*=-1.;"
         "}"
       "else"
         "{"
           "x=n(x);"
           "vec3 O=M(U,1.,x);"
           "k=O;"
         "}"
       "S=.01/abs(dot(k,U));"
       "g=t.pos+S*k;"
     "}"
   "if(!R)"
     "d*=2.;"
   "vec3 O=vec3(.001);"
   "d=mix(d,O,saturate(1.-exp2(-.0006*pow(h-length(c*.666),5.))));"
   "d*=s(-W+.25);"
   "return vec4(d,1);"
 "}"
 "void main()"
 "{"
   "gl_FragColor=o(gl_FragCoord.xy);"
 "}";

#endif // FRAG_DRAW_H_
