/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_IFRAME "m"
# define VAR_IRESOLUTION "v"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)uniform vec4 v;"
 "layout(location=1)uniform int m;\n"
 "#define PI 3.1415926\n"
 "vec3 s(in float v,in vec3 m,in vec3 y,in vec3 i,in vec3 x)"
 "{"
   "return m+y*cos(6.28318*(i*v+x));"
 "}"
 "vec3 s(float v)"
 "{"
   "return s(v,vec3(.5,.5,.5),vec3(.5,.5,.5),vec3(1.,1.,1.),vec3(0.,.33,.67));"
 "}"
 "vec2 n(vec2 v)"
 "{"
   "v+=1.61803;"
   "vec3 f=fract(vec3(v.xyx)*vec3(.1031,.103,.0973));"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.xx+f.yz)*f.zy);"
 "}"
 "const uint d=1103515245U;"
 "vec3 x(vec3 v)"
 "{"
   "uvec3 f=uvec3(v);"
   "f=(f>>8U^f.yzx)*d;"
   "f=(f>>8U^f.yzx)*d;"
   "f=(f>>8U^f.yzx)*d;"
   "return vec3(f)*(1./float(-1U));"
 "}"
 "float t(vec3 v)"
 "{"
   "return x(v).x;"
 "}"
 "vec2 e(vec2 v)"
 "{"
   "float f=v.x*2.*PI,i=sqrt(v.y);"
   "return vec2(i*cos(f),i*sin(f));"
 "}"
 "vec3 f(vec2 v)"
 "{"
   "return vec3(.2);"
 "}"
 "bool k;\n"
 "#define saturate(x)clamp(x,0.,1.)\n"
 "float e(float v,float y,float x)"
 "{"
   "float f=clamp(.5+.5*((v-y)/x),0.,1.);"
   "return(1.-f)*v+f*y-f*(1.-f)*x;"
 "}"
 "float f(float v,float m,float f)"
 "{"
   "return-e(-v,-m,f);"
 "}"
 "float n(float v,float f,float x)"
 "{"
   "vec2 m=max(vec2(x-v,x-f),vec2(0));"
   "return max(x,min(v,f))-length(m);"
 "}"
 "float s(float v,float f,float x)"
 "{"
   "vec2 m=max(vec2(x+v,x+f),vec2(0));"
   "return min(-x,max(v,f))+length(m);"
 "}"
 "float t(float v,float f,float x)"
 "{"
   "return min(e(v,f,x),n(v,f,x));"
 "}"
 "float x(float v,float m,float x)"
 "{"
   "return max(f(v,m,x),s(v,m,x));"
 "}"
 "void e(inout vec2 v,float x)"
 "{"
   "v=cos(x)*v+sin(x)*vec2(v.y,-v.x);"
 "}"
 "void r(inout vec2 v)"
 "{"
   "v=(v+vec2(v.y,-v.x))*sqrt(.5);"
 "}"
 "vec3 f(vec3 v,float f)"
 "{"
   "return e(v.yz,f),v;"
 "}"
 "vec3 n(vec3 v,float f)"
 "{"
   "return e(v.xz,f),v;"
 "}"
 "vec3 r(vec3 v,float f)"
 "{"
   "return e(v.xy,f),v;"
 "}"
 "float h(vec3 v)"
 "{"
   "return min(min(v.x,v.y),v.z);"
 "}"
 "float l(vec3 v)"
 "{"
   "return max(max(v.x,v.y),v.z);"
 "}"
 "float p(vec2 v)"
 "{"
   "return max(v.x,v.y);"
 "}"
 "float h(vec3 v,vec3 x)"
 "{"
   "vec3 f=abs(v)-x;"
   "return length(max(f,vec3(0)))+l(min(f,vec3(0)));"
 "}"
 "float l(vec2 v,vec2 x)"
 "{"
   "vec2 f=abs(v)-x;"
   "return length(max(f,vec2(0)))+p(min(f,vec2(0)));"
 "}struct Material{vec3 albedo;float specular;float roughness;};struct Model{float d;vec3 uvw;vec3 albedo;int id;};"
 "Material p(Model v,inout vec3 x)"
 "{"
   "int f=v.id;"
   "vec3 m=v.uvw;"
   "return Material(v.albedo,0.,0.);"
 "}"
 "float i;"
 "mat3 s(vec3 v,vec3 f)"
 "{"
   "vec3 x=normalize(v),i=normalize(cross(x,f)),y=normalize(cross(i,x));"
   "return mat3(i,x,y);"
 "}"
 "vec3 h(vec3 v,vec3 f,vec3 x)"
 "{"
   "return v*s(f,x);"
 "}"
 "float t(vec3 v,vec3 f)"
 "{"
   "float i=h(f,v);"
   "i=max(i,-abs(f.x));"
   "i=max(i,-(i+h(v)*.333));"
   "return i;"
 "}"
 "float l(float v,float f,float x)"
 "{"
   "return(x-v)/(f-v);"
 "}"
 "float e(bool v,vec3 f,vec3 m,vec3 i,float y)"
 "{"
   "i.y=max(i.y,.5*f.y/m.y);"
   "i.y-=f.y*.5;"
   "f.y*=.5;"
   "float d=1.,s=h(i,f*vec3(1.5,1.4,1.5));"
   "if(s>d)"
     "return s;"
   "vec3 n=i;"
   "float r=1e+12;"
   "for(int M=0;M<int(m.x);M++)"
     "{"
       "for(int l=0;l<int(m.y);l++)"
         "{"
           "for(int b=0;b<int(m.z);b++)"
             "{"
               "i=n;"
               "vec3 c=vec3(M,l,b);"
               "i-=((c+.5)/m-.5)*f*2.;"
               "vec3 P=f/m,a=x(c+11.+y);"
               "i-=(a*2.-1.)*P*.5;"
               "float z=t(c*10.+27.+y);"
               "P*=mix(.6,1.5,z);"
               "P.xz*=mix(1.8,.45,pow(float(l)/(m.y-1.),.5));"
               "float H=h(i,P);"
               "H=max(H,-abs(i.x));"
               "if(a.z>.5&&c.y>0.)"
                 "H=max(H,-abs(i.y-(z*2.-1.)*P.y*.5));"
               "r=min(r,H);"
             "}"
         "}"
     "}"
   "r=max(r,-(r+h(f/m)*.5));"
   "r=mix(r,s,smoothstep(d*.8,d,s));"
   "return r;"
 "}"
 "float e(bool v,vec3 f,vec3 x,vec3 i)"
 "{"
   "f*=.9;"
   "i.y-=f.y*.5;"
   "f.y*=.5;"
   "float m=1.,y=h(i,f*vec3(1.2,1.8,1.2));"
   "if(y>m)"
     "return y;"
   "vec3 n=i;"
   "float r=1e+12;"
   "for(int M=0;M<int(x.x);M++)"
     "{"
       "for(int s=0;s<int(x.y);s++)"
         "{"
           "for(int d=0;d<int(x.z);d++)"
             "{"
               "i=n;"
               "vec3 c=vec3(M,s,d);"
               "i-=((c+.5)/x-.5)*f*2.;"
               "vec3 b=f/x;"
               "float l=t(c+15.);"
               "b*=mix(1.1,1.75,l);"
               "float H=h(i,b)+.01;"
               "if(c==vec3(0))"
                 "H=max(H,-abs(i.x));"
               "H=max(H,-r);"
               "r=min(r,H);"
             "}"
         "}"
     "}"
   "r=max(r,-(r+h(f/x)*.5));"
   "r=mix(r,y,smoothstep(m*.8,m,y));"
   "return r;"
 "}"
 "float x(vec3 v,bool f)"
 "{"
   "float i=1e+12,x=.2;"
   "i=e(f,vec3(.35,1.6,.35),vec3(2,3,2),h(v-vec3(.8,0,-.8),vec3(.2,1,-.5),vec3(1,0,1)),0.);"
   "i=e(i,t(vec3(.13),h(v-vec3(1.8,-.15,-.3),vec3(0,1,0),vec3(1,0,-.25))),x);"
   "i=e(i,e(f,vec3(.3,.35,.3),vec3(2,1,2),h(v-vec3(-.3,0,.5),vec3(0.,1,.2),vec3(0.,0,1))-vec3(0,-.2,0)),x);"
   "i=e(i,e(f,vec3(.15,1.,.15),vec3(1,3,1),h(v-vec3(-1.8,-.15,-2.3),vec3(-1,2,-.5),vec3(-1,0,-2)),11.),x);"
   "return i;"
 "}"
 "Model c(vec3 v)"
 "{"
   "vec2 f=vec2(.43,.43);"
   "e(v.yz,(.5-f.y)*PI);"
   "e(v.xz,(.5-f.x)*PI*2.5);"
   "v.y+=.6;"
   "v.xz-=vec2(-1,1)*.4;"
   "float r=v.y+.25;"
   "r=e(r,length(v-vec3(.6,-2.5,-.7))-2.5,.6);"
   "r=e(r,length(v-vec3(-.3,-.5,.5))-.5,.4);"
   "bool m=false;"
   "float y=x(v,m),H=pow(y+.333,.5)*1.5,d=7.;"
   "r+=cos(max(H,0.)*d*PI*2.)*.015;"
   "Model s=Model(r,v,vec3(3),3),n=Model(y*i,v,vec3(1),1);"
   "if(n.d<s.d)"
     "s=n;"
   "return s;"
 "}"
 "const float y=1.73205;"
 "vec3 M(in vec3 v)"
 "{"
   "vec3 f=vec3(0.);"
   "for(int i=0;i<4;i++)"
     "{"
       "vec3 x=.5773*(2.*vec3(i+3>>1&1,i>>1&1,i&1)-1.);"
       "f+=x*c(v+.001*x).d;"
     "}"
   "return normalize(f);"
 "}"
 "vec3 H=normalize(vec3(5,2,2))*2.;struct Hit{Model model;vec3 pos;float len;float steps;};"
 "Hit M(vec3 v,vec3 f,float x,float m)"
 "{"
   "vec3 i;"
   "float r,d=0.;"
   "Model n;"
   "for(int M=0;M<200;M++)"
     "{"
       "i=v+f*r;"
       "n=c(i);"
       "r+=n.d*m;"
       "if(abs(n.d)/r<.0002)"
         "break;"
       "if(r>x)"
         "{"
           "n.id=0;"
           "break;"
         "}"
     "}"
   "return Hit(n,i,r,0.);"
 "}"
 "Hit c(vec3 v,vec3 f,float x,float m)"
 "{"
   "vec3 i;"
   "float r=0.,n=0.;"
   "Model s;"
   "float y=0.;"
   "for(float M=0.;M<100.;M++)"
     "{"
       "r+=n;"
       "i=v+r*f;"
       "s=c(i);"
       "n=s.d;"
       "y+=1.;"
       "if(abs(s.d)/r<.0002)"
         "{"
           "break;"
         "}"
       "if(r>=x)"
         "{"
           "r=x;"
           "s.id=0;"
           "break;"
         "}"
     "}"
   "return Hit(s,i,r,y);"
 "}"
 "vec3 w(vec3 v)"
 "{"
   "vec3 f=cross(vec3(-1,-1,.5),v);"
   "return f;"
 "}"
 "vec3 M(vec3 v,float f,vec2 x)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(w(v)),i=normalize(cross(v,y));"
   "vec2 m=x;"
   "m.x=m.x*2.*PI;"
   "m.y=pow(m.y,1./(f+1.));"
   "float r=sqrt(1.-m.y*m.y);"
   "return cos(m.x)*r*y+sin(m.x)*r*i+m.y*v;"
 "}"
 "vec3 c(vec3 v,float f,vec2 x)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(w(v)),i=normalize(cross(v,y));"
   "vec2 m=x;"
   "m.x=m.x*2.*PI;"
   "m.y=1.-m.y*f;"
   "float r=sqrt(1.-m.y*m.y);"
   "return cos(m.x)*r*y+sin(m.x)*r*i+m.y*v;"
 "}"
 "vec3 a=vec3(.9,.83,1);"
 "float M(vec3 v,vec3 f,vec3 m,vec3 x,vec3 y,out vec2 i)"
 "{"
   "float r=dot(x,m-v)/dot(f,x);"
   "vec3 s=v+r*f,d=cross(x,y),H=cross(x,d);"
   "s-=m;"
   "i=vec2(dot(d,s),dot(H,s));"
   "return max(sign(r),0.);"
 "}"
 "mat3 u(vec2 v)"
 "{"
   "float f=v.x,x=v.y,y=cos(f),i=cos(x),r=sin(f),m=sin(x);"
   "return mat3(i,-m*-r,-m*y,0,y,r,m,i*-r,i*y);"
 "}"
 "mat3 b;"
 "vec3 M(vec3 v,vec3 f)"
 "{"
   "v=-v;"
   "f=-f;"
   "v*=b;"
   "f*=b;"
   "vec2 x;"
   "vec3 i=vec3(-6);"
   "float m=M(v,f,i,normalize(i),normalize(vec3(-1,1,0)),x),r=smoothstep(.75,0.,l(x,vec2(.5,2))-1.);"
   "r*=smoothstep(6.,0.,length(x));"
   "return vec3(r)*m*2.;"
 "}"
 "vec4 P(vec2 f)"
 "{"
   "vec2 x=n(f+float(m)*y);"
   "i=1.;"
   "b=u((vec2(81.5,119)/vec2(187)*2.-1.)*2.);"
   "vec2 r=(-v.xy+2.*f)/v.y;"
   "r+=2.*(x-.5)/v.xy;"
   "vec3 H=vec3(0);"
   "float d=3.;"
   "vec3 l=vec3(0,0,1.5)*d,z=vec3(0,0,0);"
   "l.xy+=e(x)*.05;"
   "x=n(x);"
   "vec3 P=normalize(z-l),o=normalize(cross(vec3(0,1,0),P)),I=normalize(cross(P,o));"
   "mat3 w=mat3(-o,I,P);"
   "vec3 k=normalize(w*vec3(r.xy,d)),g=l;"
   "Hit t=c(g,k,4.*d,1.);"
   "float h=t.len,U=t.steps;"
   "vec3 q,F,C;"
   "Material Z;"
   "vec3 Y=vec3(1),X=a;"
   "int W=10;"
   "float V=x.y,T=0.,S,R;"
   "bool Q=t.model.id==1;"
   "for(int O=0;O<W;O++)"
     "{"
       "if(O>0)"
         "x=n(x),t=c(g,k,6.,1.);"
       "if(i<0.)"
         "T+=t.len;"
       "if(t.model.id==0)"
         "{"
           "break;"
         "}"
       "q=M(t.pos);"
       "Z=p(t.model,q);"
       "Y*=Z.albedo;"
       "if(t.model.id==1)"
         "{"
           "F=reflect(k,q);"
           "H+=M(t.pos,F)*.5;"
           "H+=pow(max(1.-abs(dot(k,q)),0.),5.)*.1;"
           "H*=vec3(.85,.85,.98);"
           "S=mix(1.2,1.8,V);"
           "S=i<0.?S:1./S;"
           "C=refract(k,q,S);"
           "bool N=C==vec3(0);"
           "k=N?F:C;"
           "i*=-1.;"
         "}"
       "else"
         "{"
           "x=n(x);"
           "vec3 N=M(q,1.,x);"
           "k=N;"
         "}"
       "R=.01/abs(dot(k,q));"
       "g=t.pos+R*k;"
     "}"
   "if(!Q)"
     "H*=1.5;"
   "vec3 N=vec3(.001);"
   "H=mix(H,N,saturate(1.-exp2(-.0006*pow(h-length(l*.666),5.))));"
   "H*=s(-V+.25);"
   "return vec4(H,1);"
 "}"
 "void main()"
 "{"
   "gl_FragColor=P(gl_FragCoord.xy);"
 "}";

#endif // FRAG_DRAW_H_
