/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_IFRAME "x"
# define VAR_IRESOLUTION "v"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)uniform vec4 v;"
 "layout(location=1)uniform int x;\n"
 "#define PI 3.1415926\n"
 "vec3 t(in float v,in vec3 y,in vec3 x,in vec3 m,in vec3 z)"
 "{"
   "return y+x*cos(6.28318*(m*v+z));"
 "}"
 "vec3 t(float v)"
 "{"
   "return t(v,vec3(.5,.5,.5),vec3(.5,.5,.5),vec3(1.,1.,1.),vec3(0.,.33,.67));"
 "}"
 "vec2 s(vec2 v)"
 "{"
   "v+=1.61803;"
   "vec3 f=fract(vec3(v.xyx)*vec3(.1031,.103,.0973));"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.xx+f.yz)*f.zy);"
 "}"
 "const uint d=1103515245U;"
 "vec3 n(vec3 v)"
 "{"
   "uvec3 f=uvec3(v);"
   "f=(f>>8U^f.yzx)*d;"
   "f=(f>>8U^f.yzx)*d;"
   "f=(f>>8U^f.yzx)*d;"
   "return vec3(f)*(1./float(-1U));"
 "}"
 "float m(vec3 v)"
 "{"
   "return n(v).x;"
 "}\n"
 "#define saturate(x)clamp(x,0.,1.)\n"
 "float m(float v,float y,float x)"
 "{"
   "float f=clamp(.5+.5*((v-y)/x),0.,1.);"
   "return(1.-f)*v+f*y-f*(1.-f)*x;"
 "}"
 "void m(inout vec2 v,float x)"
 "{"
   "v=cos(x)*v+sin(x)*vec2(v.y,-v.x);"
 "}"
 "float e(vec3 v)"
 "{"
   "return min(min(v.x,v.y),v.z);"
 "}"
 "float f(vec3 v)"
 "{"
   "return max(max(v.x,v.y),v.z);"
 "}"
 "float r(vec2 v)"
 "{"
   "return max(v.x,v.y);"
 "}"
 "float e(vec3 v,vec3 x)"
 "{"
   "vec3 m=abs(v)-x;"
   "return length(max(m,vec3(0)))+f(min(m,vec3(0)));"
 "}"
 "float f(vec2 v,vec2 x)"
 "{"
   "vec2 m=abs(v)-x;"
   "return length(max(m,vec2(0)))+r(min(m,vec2(0)));"
 "}"
 "mat3 n(vec3 v,vec3 x)"
 "{"
   "vec3 f=normalize(v),m=normalize(cross(f,x)),y=normalize(cross(m,f));"
   "return mat3(m,f,y);"
 "}"
 "vec3 e(vec3 v,vec3 m,vec3 x)"
 "{"
   "return v*n(m,x);"
 "}"
 "vec2 c(vec2 v)"
 "{"
   "float x=v.x*2.*PI,f=sqrt(v.y);"
   "return vec2(f*cos(x),f*sin(x));"
 "}"
 "float c(float v,float m,float x)"
 "{"
   "return(x-v)/(m-v);"
 "}"
 "float y;struct Model{float d;int id;};"
 "float c(vec3 v,vec3 x)"
 "{"
   "float f=e(x,v);"
   "f=max(f,-abs(x.x));"
   "f=max(f,-(f+e(v)*.333));"
   "return f;"
 "}"
 "float c(vec3 v,vec3 x,vec3 f,float y)"
 "{"
   "f.y=max(f.y,.5*v.y/x.y);"
   "f.y-=v.y*.5;"
   "v.y*=.5;"
   "float i=1.,d=e(f,v*vec3(1.5,1.4,1.5));"
   "if(d>i)"
     "return d;"
   "vec3 s=f;"
   "float r=1e+12;"
   "for(int c=0;c<int(x.x);c++)"
     "for(int z=0;z<int(x.y);z++)"
       "for(int l=0;l<int(x.z);l++)"
         "{"
           "f=s;"
           "vec3 M=vec3(c,z,l);"
           "f-=((M+.5)/x-.5)*v*2.;"
           "vec3 P=v/x,I=n(M+11.+y);"
           "f-=(I*2.-1.)*P*.5;"
           "float p=m(M*10.+27.+y);"
           "P*=mix(.6,1.5,p);"
           "P.xz*=mix(1.8,.45,pow(float(z)/(x.y-1.),.5));"
           "float H=e(f,P);"
           "H=max(H,-abs(f.x));"
           "if(I.z>.5&&M.y>0.)"
             "H=max(H,-abs(f.y-(p*2.-1.)*P.y*.5));"
           "r=min(r,H);"
         "}"
   "r=max(r,-(r+e(v/x)*.5));"
   "r=mix(r,d,smoothstep(i*.8,i,d));"
   "return r;"
 "}"
 "float f(vec3 v,vec3 x,vec3 f)"
 "{"
   "v*=.9;"
   "f.y-=v.y*.5;"
   "v.y*=.5;"
   "float y=1.,d=e(f,v*vec3(1.2,1.8,1.2));"
   "if(d>y)"
     "return d;"
   "vec3 n=f;"
   "float r=1e+12;"
   "for(int i=0;i<int(x.x);i++)"
     "for(int l=0;l<int(x.y);l++)"
       "for(int z=0;z<int(x.z);z++)"
         "{"
           "f=n;"
           "vec3 c=vec3(i,l,z);"
           "f-=((c+.5)/x-.5)*v*2.;"
           "vec3 H=v/x;"
           "float s=m(c+15.);"
           "H*=mix(1.1,1.75,s);"
           "float M=e(f,H)+.01;"
           "if(c==vec3(0))"
             "M=max(M,-abs(f.x));"
           "M=max(M,-r);"
           "r=min(r,M);"
         "}"
   "r=max(r,-(r+e(v/x)*.5));"
   "r=mix(r,d,smoothstep(y*.8,y,d));"
   "return r;"
 "}"
 "float p(vec3 v)"
 "{"
   "float r=1e+12,x=.2;"
   "r=c(vec3(.35,1.6,.35),vec3(2,3,2),e(v-vec3(.8,0,-.8),vec3(.2,1,-.5),vec3(1,0,1)),0.);"
   "r=m(r,c(vec3(.13),e(v-vec3(1.8,-.15,-.3),vec3(0,1,0),vec3(1,0,-.25))),x);"
   "r=m(r,f(vec3(.3,.35,.3),vec3(2,1,2),e(v-vec3(-.3,0,.5),vec3(0.,1,.2),vec3(0.,0,1))-vec3(0,-.2,0)),x);"
   "r=m(r,c(vec3(.15,1.,.15),vec3(1,3,1),e(v-vec3(-1.8,-.15,-2.3),vec3(-1,2,-.5),vec3(-1,0,-2)),11.),x);"
   "return r;"
 "}"
 "Model P(vec3 v)"
 "{"
   "vec2 f=vec2(.43,.43);"
   "m(v.yz,(.5-f.y)*PI);"
   "m(v.xz,(.5-f.x)*PI*2.5);"
   "v.y+=.6;"
   "v.xz-=vec2(-1,1)*.4;"
   "float r=v.y+.25;"
   "r=m(r,length(v-vec3(.6,-2.5,-.7))-2.5,.6);"
   "r=m(r,length(v-vec3(-.3,-.5,.5))-.5,.4);"
   "float x=p(v),i=pow(x+.333,.5)*1.5,d=7.;"
   "r+=cos(max(i,0.)*d*PI*2.)*.015;"
   "Model M=Model(r,2),n=Model(x*y,1);"
   "if(n.d<M.d)"
     "M=n;"
   "return M;"
 "}"
 "const float z=1.73205;"
 "vec3 h(in vec3 v)"
 "{"
   "vec3 f=vec3(0.);"
   "for(int r=0;r<4;r++)"
     "{"
       "vec3 x=.5773*(2.*vec3(r+3>>1&1,r>>1&1,r&1)-1.);"
       "f+=x*P(v+.001*x).d;"
     "}"
   "return normalize(f);"
 "}struct Hit{Model model;vec3 pos;float len;};"
 "Hit P(vec3 v,vec3 x,float m)"
 "{"
   "vec3 f;"
   "float r=0.,d=0.;"
   "Model i;"
   "for(float y=0.;y<100.;y++)"
     "{"
       "r+=d;"
       "f=v+r*x;"
       "i=P(f);"
       "d=i.d;"
       "if(abs(i.d)/r<.0002)"
         "{"
           "break;"
         "}"
       "if(r>=m)"
         "{"
           "r=m;"
           "i.id=0;"
           "break;"
         "}"
     "}"
   "return Hit(i,f,r);"
 "}"
 "vec3 i(vec3 v)"
 "{"
   "vec3 f=cross(vec3(-1,-1,.5),v);"
   "return f;"
 "}"
 "vec3 h(vec3 v,float f,vec2 x)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(i(v)),r=normalize(cross(v,y));"
   "vec2 m=x;"
   "m.x=m.x*2.*PI;"
   "m.y=pow(m.y,1./(f+1.));"
   "float d=sqrt(1.-m.y*m.y);"
   "return cos(m.x)*d*y+sin(m.x)*d*r+m.y*v;"
 "}"
 "vec3 i(vec3 v,float x,vec2 m)"
 "{"
   "v=normalize(v);"
   "vec3 f=normalize(i(v)),r=normalize(cross(v,f));"
   "vec2 d=m;"
   "d.x=d.x*2.*PI;"
   "d.y=1.-d.y*x;"
   "float y=sqrt(1.-d.y*d.y);"
   "return cos(d.x)*y*f+sin(d.x)*y*r+d.y*v;"
 "}"
 "float P(vec3 v,vec3 f,vec3 m,vec3 x,vec3 y,out vec2 r)"
 "{"
   "float d=dot(x,m-v)/dot(f,x);"
   "vec3 i=v+d*f,z=cross(x,y),M=cross(x,z);"
   "i-=m;"
   "r=vec2(dot(z,i),dot(M,i));"
   "return max(sign(d),0.);"
 "}"
 "mat3 l(vec2 v)"
 "{"
   "float x=v.x,f=v.y,y=cos(x),r=cos(f),d=sin(x),m=sin(f);"
   "return mat3(r,-m*-d,-m*y,0,y,d,m,r*-d,r*y);"
 "}"
 "mat3 M;"
 "vec3 P(vec3 v,vec3 x)"
 "{"
   "v=-v;"
   "x=-x;"
   "v*=M;"
   "x*=M;"
   "vec2 m;"
   "vec3 r=vec3(-6);"
   "float y=P(v,x,r,normalize(r),normalize(vec3(-1,1,0)),m),i=smoothstep(.75,0.,f(m,vec2(.5,2))-1.);"
   "i*=smoothstep(6.,0.,length(m));"
   "return vec3(i)*y*2.;"
 "}"
 "float w(vec3 v)"
 "{"
   "return dot(v,vec3(.2126,.7152,.0722));"
 "}"
 "vec4 a(vec2 f)"
 "{"
   "vec2 r=s(f+float(x)*z);"
   "y=1.;"
   "M=l((vec2(81.5,119)/vec2(187)*2.-1.)*2.);"
   "vec2 m=(-v.xy+2.*f)/v.y;"
   "m+=2.*(r-.5)/v.xy;"
   "float d=3.;"
   "vec3 i=vec3(0,0,1.5)*d,n=vec3(0,0,0);"
   "i.xy+=c(r)*.05;"
   "r=s(r);"
   "vec3 H=normalize(n-i),a=normalize(cross(vec3(0,1,0),H)),p=normalize(cross(H,a));"
   "mat3 I=mat3(-a,p,H);"
   "vec3 b=normalize(I*vec3(m.xy,d)),o=i;"
   "Hit u=P(o,b,4.*d);"
   "float e=u.len;"
   "bool w=u.model.id==2;"
   "vec3 g,U,k;"
   "float q,F,C=r.y;"
   "vec3 Z=vec3(0);"
   "for(int Y=0;Y<10;Y++)"
     "{"
       "if(Y>0)"
         "r=s(r),u=P(o,b,6.);"
       "if(u.model.id==0)"
         "{"
           "break;"
         "}"
       "g=h(u.pos);"
       "if(u.model.id==1)"
         "{"
           "U=reflect(b,g);"
           "Z+=P(u.pos,U)*.5;"
           "Z+=pow(max(1.-abs(dot(b,g)),0.),5.)*.1;"
           "Z*=vec3(.85,.85,.98);"
           "q=mix(1.2,1.8,C);"
           "q=y<0.?q:1./q;"
           "k=refract(b,g,q);"
           "bool X=k==vec3(0);"
           "b=X?U:k;"
           "y*=-1.;"
         "}"
       "else"
         " r=s(r),b=h(g,1.,r);"
       "F=.01/abs(dot(b,g));"
       "o=u.pos+F*b;"
     "}"
   "if(w)"
     "Z*=2.;"
   "vec3 Y=vec3(0.);"
   "Z=mix(Z,Y,saturate(1.-exp2(-.0006*pow(e-length(i*.666),5.))));"
   "Z*=t(-C+.3);"
   "return vec4(Z,1);"
 "}"
 "void main()"
 "{"
   "gl_FragColor=a(gl_FragCoord.xy);"
 "}";

#endif // FRAG_DRAW_H_
